name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate
          pnpm -v

      - name: Install (workspace)
        run: pnpm -w install

      - name: Sanity — cors types in API
        run: pnpm -C apps/api ls @types/cors

      - name: Build API
        working-directory: apps/api
        run: pnpm build

      - name: Build Web
        working-directory: apps/web
        run: pnpm next build --no-lint
